### ISSUE TITLE
Android armv7a compilation broken with Node 16.17.1

### ISSUE THREAD

**Issue by staltz** [nodejs-mobile/nodejs-mobile#10]
Affects `main` branch right now. Compilation for armv7a fails with

```
Error: bad register name `%rbp'
Error: bad register name `%rsp'
Error: bad register name `%rbx'
Error: bad register name `%r12'
Error: bad register name `%r13'
Error: bad register name `%r14'
Error: bad register name `%r15'
Error: bad register name `%rdx'
Error: bad register name `%rsp'
Error: bad register name `%r8'
Error: bad register name `%rsp'
Error: bad register name `%rbp'
```

when building the target `deps/v8/src/heap/base/asm/x64/push_registers_asm.cc` as part of building `v8_base_without_compiler`.

**Comment by staltz** [comment]
Fixed with https://github.com/nodejs-mobile/nodejs-mobile/commit/25220536b13d9d3b84b34089ba469697de176030

**Comment by anrefst** [comment]
Hello, I get the same problem when I build x86 on latest main branch. X64 does not have the problem.
