### ISSUE TITLE
Upgrade to Node.js v18.20.4

### ISSUE THREAD

**Issue by staltz** [nodejs-mobile/nodejs-mobile#126]
We should catch up with the original Node.js "Active LTS" which is 18.20.4.

**Comment by jsamol** [comment]
The current "Active LTS" is v20.17.0, v18.20.4 was moved to "Maintenance LTS" in October 2023. What's more, v20.17.0 is about to be moved to "Maintenance LTS" itself and replaced with v22.x by the end of this month, pushing v18.20.4 away from any LTS track.

Having said that, if you want to catch up with the original Node.js "Active LTS", shouldn't you be looking at v20.17.0 or even v22 instead?
