### ISSUE TITLE
Support for capacitor.js 

### ISSUE THREAD

**Issue by sau4321** [nodejs-mobile/nodejs-mobile#137]
Does it support capacitor.js or maybe can I integrate it in the /android folder of my capacitor.js+react app can anyone help me with this?

**Comment by sureshots-us** [comment]
https://github.com/hampoelz/Capacitor-NodeJS it's already here and working. (Although it is not published on npm)  it's out of scope for nodejs-mobile itself though. The react-native plugin is also separate from this repo.

**Comment by sau4321** [comment]
I tried it, but I was not able to get it working. I don't know where I went wrong if you have any idea how to get it working in react+vite+capacitor.js app. I am trying to create an express.js server with other npm library  inside the nodejs project and pack it inside an apk. Before doing all of that I will have to go through the development mode but my issue is I just can't get it working I am using development mode right now for building my app and viewing the live changes through the IP ADDERESS:PORT of my vite app inside the capacitor config file. I also installed the capacitor-nodejs library and followed the steps. Can you tell me the exact steps on what to to how to get it working while in development mode.

**Comment by sureshots-us** [comment]
You should file a bug there and not here and close this one.

**Comment by sau4321** [comment]
okayy got it
