### ISSUE TITLE
How to let 'import' and 'require' to work togethor?

### ISSUE THREAD

**Issue by wangfaguo** [nodejs-mobile/nodejs-mobile#16]
### Version

16.17.1

### Platform

Darwin xxxxxxMac-mini.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:35 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T8101 arm64

### Subsystem

don't know

### What steps will reproduce the bug?

var http = require('http');

// var leftPad = require('left-pad');
var versions_server = http.createServer( (request, response) => {
 response.end('Versions1: ' + JSON.stringify(process.versions) + ' left-pad: 0');
 rn_bridge.channel.send("server is visited.");
});
versions_server.listen(3001);

import { createLibp2p } from './libp2p.js'

xxxxxxx

### How often does it reproduce? Is there a required condition?

package.json

{
  "//": [
    "Rename this sample file to package.json to use on your project.",
    "The sample-package.json file will be overwritten in updates/reinstalls."
  ],
  "name": "sample-node-project",
  "version": "0.0.1",
  "description": "node part of the project",
  "main": "main.js",
  "author": "janeasystems",
  "license": "ISC",
  "type":"module",
  "dependencies": {
    "@chainsafe/libp2p-noise": "^10.2.0",
    "@libp2p/bootstrap": "^5.0.0",
    "@libp2p/mplex": "^7.0.5",
    "@libp2p/tcp": "^6.0.4",
    "@libp2p/websockets": "^5.0.0",
    "@nodeutils/defaults-deep": "^1.1.0",
    "libp2p": "^0.40.0"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": []
}

### What is the expected behavior?

GOT error

### What do you see instead?

E/nodejs: file:///data/data/com.awesomeproject/files/nodejs-project/main.js:18
    var http = require('http');
               ^
    
    ReferenceError: require is not defined in ES module scope, you can use import instead
    This file is being treated as an ES module because it has a '.js' file extension and '/data/data/com.awesomeproject/files/nodejs-project/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
        at file:///data/data/com.awesomeproject/files/nodejs-project/main.js:18:12
        at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
        at async Promise.all (index 0)
        at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
        at async loadESM (node:internal/process/esm_loader:91:5)
        at async handleMainPromise (node:internal/modules/run_main:65:12)
E/NODEJS-MOBILE: exiting due to SIG_DFL handler for signal 11
I/BpBinder: onLastStrongRef automatically unlinking death recipients: <uncached descriptor>
A/libc: exiting due to SIG_DFL handler for signal 11
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 18857 (FlipperEventBas), pid 18724 (.awesomeproject)

### Additional information

thanks

**Comment by staltz** [comment]
You have an ESM and `require` question, which should be fairly easy to get an answer from Stackoverflow or Node.js (upstream) issues. This is not specific to nodejs-mobile, so I'm closing it.
