### ISSUE TITLE
Node 18.16.0 LTS support?

### ISSUE THREAD

**Issue by androidplayer1** [nodejs-mobile/nodejs-mobile#18]
### What is the problem this feature will solve?

Latest LTS version of node, should bring us more features, security patches ...

### What is the feature you are proposing to solve the problem?

Upgrade to node LTS

### What alternatives have you considered?

None

**Comment by staltz** [comment]
Will happen before Node 16 leaves LTS. Don't worry.

**Comment by JMLX42** [comment]
> Will happen before Node 16 leaves LTS. Don't worry.

Should we worry now? :smirk: 

Please let me know how we can help!

**Comment by staltz** [comment]
See #38 

Please try to keep spam at a minimum, it doesn't help me make progress.

**Comment by staltz** [comment]
Done! https://github.com/nodejs-mobile/nodejs-mobile/releases/tag/v18.17.1
