### ISSUE TITLE
Android x86 compilation broken with Node 16.17.1

### ISSUE THREAD

**Issue by anrefst** [nodejs-mobile/nodejs-mobile#19]
### Version

v16.17.0

### Platform

5.10.0-19-amd64 x86_64 GNU/Linux

### What steps will reproduce the bug?

/tools/android_build.sh /nodejs-mobile/nodejs-mobile/ndk/android-ndk-r21e/ x86 23

### How often does it reproduce? Is there a required condition?

always

### What is the expected behavior?

built libnode.so of x86

### What do you see instead?

`/tmp/cc0lFzos.s: Assembler messages:
/tmp/cc0lFzos.s:8: Error: bad register name %rbp
/tmp/cc0lFzos.s:9: Error: bad register name %rsp
/tmp/cc0lFzos.s:11: Error: bad register name %rbx
/tmp/cc0lFzos.s:12: Error: bad register name %r12
/tmp/cc0lFzos.s:13: Error: bad register name %r13
/tmp/cc0lFzos.s:14: Error: bad register name %r14
/tmp/cc0lFzos.s:15: Error: bad register name %r15
/tmp/cc0lFzos.s:16: Error: bad register name %rdx
/tmp/cc0lFzos.s:17: Error: bad register name %rsp
/tmp/cc0lFzos.s:18: Error: bad register name %r8
/tmp/cc0lFzos.s:19: Error: bad register name %rsp
/tmp/cc0lFzos.s:20: Error: bad register name %rbp
make[1]: *** [tools/v8_gypfiles/v8_base_without_compiler.host.mk:941: /nodejs-mobile/001/nodejs-mobile/out/Release/obj.host/v8_base_without_compiler/deps/v8/src/heap/base/asm/x64/push_registers_asm.o] Fehler 1
make[1]: *** Es wird auf noch nicht beendete Prozesse gewartet....
rm 135417f2bb927e97f6d96a4b54ba06bbb7e759e3.intermediate cdb84da0ee5ad0c2c2e238d51aec53052ac3b6a4.intermediate be4ceed00c50103e5c10d0e0fb86fa6bf47120ff.intermediate 2169caba587f016f3ea69841d326b3abb2c12253.intermediate
make: *** [Makefile:113: node] Fehler 2`

### Additional information

Looks like the same bug like in  #10

**Comment by CurseStaff** [comment]
same issues, up

**Comment by staltz** [comment]
Support for x86 (not x86_64) was explicitly dropped: https://github.com/nodejs-mobile/nodejs-mobile/releases/tag/nodejs-mobile-v16.17.0

It didn't seem worth the effort since this architecture (reminder: it's 32-bits!) is rare nowadays.
