### ISSUE TITLE
Consider switching away from the chakra fork and improve the offical effort

### ISSUE THREAD

**Issue by lemanschik** [nodejs-mobile/nodejs-mobile#68]
### What is the problem this feature will solve?

It will make it easyer to upgrade NodeJS and keep up with the mainline

### What is the feature you are proposing to solve the problem?

Reading https://github.com/nodejs/node/blob/HEAD/BUILDING.md#android

then trying to refactor incremental to that code base via try and error and then submit patches to mainline to get more maintainers.....

### What alternatives have you considered?

Keeping this project up which costs a lot of efforts keeping the corodova and other integrations updated is enough work already.

**Comment by staltz** [comment]
This repo is not on Chakra anymore, it's based on upstream Node.js.
