### ISSUE TITLE
Update to NodeJS 21.5.0

### ISSUE THREAD

**Issue by Soft-Buddy** [nodejs-mobile/nodejs-mobile#78]
### What is the problem this feature will solve?

Kindly update the sources to NodeJS 21.5.0. It will be very helpful.

### What is the feature you are proposing to solve the problem?

The repo should be updated to latest NodeJS version 21.5.0

**Comment by staltz** [comment]
Don't currently have the time resources for this, and we usually target LTS releases,which 21.x isn't.

**Comment by Soft-Buddy** [comment]
@staltz atleast 20.* Releases should be available.

**Comment by staltz** [comment]
We're going to keep this project up-to-date with LTS at our own reasonable pace, I don't see the point of opening an issue just to pressure us to work harder or something.
