### ISSUE TITLE
Unsupported Architecture Provided

### ISSUE THREAD

**Issue by sgtcoder** [nodejs-mobile/nodejs-mobile#82]
### Version

v20.11.0

### Platform

Linux linux1 6.1.74-x64v4-xanmod1 #0~20240120.g102f9ba SMP PREEMPT_DYNAMIC Sat Jan 20 23:15:02 UTC x86_64 GNU/Linux

### What steps will reproduce the bug?

curl https://dl.google.com/android/repository/android-ndk-r21b-linux-x86_64.zip -o ndk.zip
unzip ndk.zip

git clone https://github.com/nodejs-mobile/nodejs-mobile
cd nodejs-mobile
git checkout mobile-master

./tools/android_build.sh ~/android-ndk-r21b 28

### How often does it reproduce? Is there a required condition?

Every single time. I tried different SDK versions as well

### What is the expected behavior? Why is that the expected behavior?

I would expect the build to be successful

### What do you see instead?

Unsupported architecture provided: 28

### Additional information

Just trying my best to use the old/outdated documentation with a different modern repo. The documentation is very limited as well.

**Comment by staltz** [comment]
Try a more recent NDK, like NDK 24 or 25

**Comment by sgtcoder** [comment]
> Try a more recent NDK, like NDK 24 or 25

I had tried newer versions, but then I get

```
./android-configure: line 53: /home/USER/android-ndk-r24/build/tools/make-standalone-toolchain.sh: No such file or directory
```

Commands Ran

```
curl https://dl.google.com/android/repository/android-ndk-r24-linux.zip -o ndk.zip
unzip ndk.zip

git clone https://github.com/nodejs-mobile/nodejs-mobile
cd nodejs-mobile
git checkout mobile-master

./tools/android_build.sh ~/android-ndk-r24 28
```

**Comment by sgtcoder** [comment]
Looks like they switched to python

```
cd android-ndk-r24/build/tools

ls
make_standalone_toolchain.py
```

**Comment by sgtcoder** [comment]
I found this to work as far as building goes. But then I realized this is the same that is under the releases tab.

```
sudo apt-get install gcc-multilib g++-multilib
```

```
curl https://dl.google.com/android/repository/android-ndk-r22b-linux-x86_64.zip -o ndk.zip
unzip ndk.zip

git clone https://github.com/nodejs-mobile/nodejs-mobile
cd nodejs-mobile
git checkout mobile-master

./tools/android_build.sh ~/android-ndk-r22b
```

**Comment by sgtcoder** [comment]
I have made signifcant progress and I will share everything and the documentation.

But, I was wondering if there is a callback for `startNodeWithArguments` or something to know when node is started, it sometimes takes a few seconds so I get a connection refused while Node is still starting up.
